### ISSUE TITLE
The data download link is not avaliable

### ISSUE THREAD

**Issue by PaulZhangIsing** [jiacheng-xu/vmf_vae_nlp#11]
As suggested in README, this isssue is arised as the download link stated in README doesn't work

**Comment by jiacheng-xu** [comment]
it looks fine from my perspective.
https://utexas.box.com/s/fxx989beng9zyafv9oej180wf3vt7v1w 
What's the error message?

**Comment by PaulZhangIsing** [comment]
It says that the network was not avaliable... probably it is due to my network error. My bad
