### ISSUE TITLE
when I use yelp (with condition bit 50), I got this error message.

### ISSUE THREAD

**Issue by hyeseonko** [jiacheng-xu/vmf_vae_nlp#4]
Hi,
Thanks for sharing your code :)
I got the error if I use the dataset 'yelp'. Do you know how to fix it?
I am currently using torch 0.4.1 and cuda 9.0.

Traceback (most recent call last):
  File "D:/Generation/vMF-VAE/nvll.py", line 175, in <module>
    main()
  File "D:/Generation/vMF-VAE/nvll.py", line 170, in main
    runner.start()
  File "D:\Generation\vMF-VAE\NVLL\framework\train_eval_nvrnn.py", line 45, in start
    epoch_start_time, self.glob_iter)
  File "D:\Generation\vMF-VAE\NVLL\framework\train_eval_nvrnn.py", line 225, in train_epo
    acc_avg_cos += tup['avg_cos'].data
RuntimeError: expand(torch.cuda.FloatTensor{[1]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)

**Comment by jiacheng-xu** [comment]
It seems that it's a version issue (pytorch 0.3 or 0.4.1) which might be ignored during my test. Could you try to remove `.data` or replace `.data` with `.item()`. It should be a minor bug about dimension compatibility from 0.3 to 0.4. Let me know if it works or not. Thank you so much.

**Comment by hyeseonko** [comment]
Wow..Thank you so much for your fast reply!!!!
I will try to replace .data and if the bug is fixed, I will write down here :)
Thank you so much, again.

**Comment by hyeseonko** [comment]
As you said,
if I replace .data to .item(), it worked fine !!
Thank you so much!
